import { Geist, Geist_Mono, Roboto_Condensed } from "next/font/google";
import Image from "next/image";
import avatarImg from"@/../public/avatar.jpg";
import Link from "next/link";
import LinkImg1 from "@/image/帝寶.png";
import Image5 from "@/image/5.png";
import Image6 from "@/image/6.png";
import Image7 from "@/image/7.png";
import Image8 from "@/image/8.png";
import Image9 from "@/image/9.png";
import Image10 from "@/image/10.png";
import Image11 from "@/image/11.png";
import Image12 from "@/image/12.png";
import Image13 from "@/image/13.png";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'], // 子集，通常 latin 即可
  weight: ['400', '700'], // 選擇你需要的字重，例如 '400' (Regular), '700' (Bold)
  display: 'swap',
  variable: '--font-roboto-condensed' // 指定 CSS 變數名稱
});

export const metadata = {
  title: "Whitee的數位履歷",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoCondensed.variable} antialiased`}
      >
        {/* ===== 新增的固定 Header Bar ===== */}
        {/* 調整 w-16, pt-8, gap-y-8, bg-red-600 等數值來符合你的設計 */}
        <div className=" fixed top-0 sm:left-77 left-95 h-65 w-16 bg-red-600 flex flex-col items-start pt-37 gap-y-1 z-50">
          {/* Home 連結 (內部) */}
          <Link href="/" title="首頁">
            {/* <FaHome className="text-white text-2xl hover:text-gray-300 transition-colors" /> */}
            <span className=" inline-block scale-y-140 text-white font-extrabold hover:opacity-80 transition-colors ml-1 ">HOME</span>
          </Link>

          {/* Instagram 連結 (外部) */}
          <a
            href="https://www.instagram.com/wooper_house?igsh=MTMxNXpxZzR2bWltag%3D%3D&utm_source=qr" // <-- 換成你的連結
            target="_blank"
            rel="noopener noreferrer"
            title="Instagram"
          >
            {/* <FaInstagram className="text-white text-2xl hover:text-gray-300 transition-colors" /> */}
             <span className=" inline-block scale-y-140 text-white font-extrabold hover:opacity-80 transition-colors ml-1">IG</span>
          </a>

          {/* Behance 連結 (外部) */}
          <a
            href="https://www.behance.net/8ab16535?fbclid=PAZXh0bgNhZW0CMTEAAaeNuOADEbpqK9TzUo-fMnLbmJRO8GZuucngDFMb5BW3F6IVcGYuA4JVWEOIKA_aem_r_3kzRJUlOfhnVJ_Ruj-sw" // <-- 換成你的連結
            target="_blank"
            rel="noopener noreferrer"
            title="Behance"
          >
            {/* <FaBehanceSquare className="text-white text-2xl hover:text-gray-300 transition-colors" /> */}
             <span className=" inline-block scale-y-140 text-white font-extrabold hover:opacity-80 transition-colors ml-1">BE</span>
          </a>

          {/* Email 連結 */}
          <a href="mailto:wooperhouse@gmail.com" title="Email"> {/* <-- 換成你的 Email */}
            {/* <FaEnvelope className="text-white text-2xl hover:text-gray-300 transition-colors" /> */}
             <span className="inline-block scale-y-140 text-white font-extrabold hover:opacity-80 transition-colors ml-10 text-xl -translate-y-1.5">@</span>
          </a>
        </div>

      
      


        <div className="w-screen h-screen sm:full overflow-y-auto flex flex-col sm:flex-row gap-5 p-8   bg-[linear-gradient(to_bottom,#d7ecea_60%,#97cac4)]">

          <div className="min-w-[360px] w-full sm:w-[320px]  h-auto sm:h-full  bg-white/0 flex justify-start items-start flex-col p-[5px] pt-[15px] overflow-y-auto overflow-x-hidden shrink-0">
            
            <Image src={avatarImg} alt="avatar" className="w-[120px] h-[120px] rounded-full"/>
            <span className="mt-3 font-semibold text-[#1c4f53] ">白苡詰</span>
            <span className=" max-w-[380px] text-center text-[#1c4f53] font-semibold">
                國立政治大學 經濟四甲
            </span>

            {/*社群連結 */}




           

            <div className="  sm:flex-grow sm:h-full sm:overflow-y-auto w-full flex flex-col gap-y-8 items-start mt-12">
              <div className=" w-full flex flex-row items-center ">
                  <Link href="/about">
                    <div className="inline-block hover:opacity-80 transition-opacity rounded-lg ">
                      <Image
                      src={Image5}         
                      alt="關於我頁面連結"    
                      width={150}
                      height={150} />                        
                    </div>
                  </Link>
                  <Link href="/about"> {/* 同樣連結到 /about */} 
                    <div className="inline-block hover:opacity-80 transition-opacity rounded-lg mt-15"> {/* 移除 -ml-1 */}
                      <Image
                      src={Image8}
                      alt="關於我頁面連結 - 圖2"
                      width={100}
                      height={100} />
                    </div>
                  </Link>
              </div> 

              <div className="w-full flex flex-row justify-end items-center gap-x-3 self-end">
                  <Link href="/cate-web">
                    <div className="inline-block hover:opacity-80 transition-opacity rounded-lg mt-9 translate-x-3">
                      <Image
                        src={Image9}         
                        alt="關於我頁面連結"    
                        width={140}
                        height={140} />
                    </div>
                  </Link>
                  <Link href="/cate-web">
                    <div className="inline-block hover:opacity-80 transition-opacity rounded-lg">
                      <Image
                      src={Image6}         
                      alt="關於我頁面連結"    
                      width={160} height={160} />                        
                    </div>
                  </Link>
              </div>

              <div className="w-full flex flex-row items-center">
                  <Link href="/cate-painting">
                   <div className="inline-block hover:opacity-80 transition-opacity rounded-lg">
                      <Image src={Image7} alt="Cate-Painting - 圖1" width={130} height={130} />
                     </div>
                  </Link>
                  <Link href="/cate-painting">
                     <div className="inline-block hover:opacity-80 transition-opacity rounded-lg mt-18 ml-2">
                       <Image src={Image10} alt="Cate-Painting - 圖2" width={130} height={130} />
                    </div>
                   </Link>
              </div>

              <div className="w-full flex flex-row justify-end items-center gap-x-0 self-end">
                  <Link href="/cate-keyvisual">
                    <div className="inline-block hover:opacity-80 transition-opacity rounded-lg  mt-18 translate-x-4">
                      <Image
                        src={Image12}         
                        alt="關於我頁面連結"    
                        width={160}
                        height={160} />
                    </div>
                  </Link>
                  <Link href="/cate-keyvisual">
                    <div className="inline-block hover:opacity-80 transition-opacity rounded-lg ">
                      <Image
                      src={Image11}         
                      alt="關於我頁面連結"    
                      width={210} height={210} />                        
                    </div>
                  </Link>
              </div>

                  

             
          
              
              
            </div>

          </div>

          {children}

        </div>

      </body>
    </html>
  );
}
