import { Geist, Geist_Mono, Roboto_Condensed } from "next/font/google";
import "@/../src/app/globals.css";
import Image from "next/image";
import avatarImg from"@/../public/avatar.jpg";
import Link from "next/link";
import LinkImg1 from "@/image/帝寶.png";
import Image5 from "@/image/5.png";
import Image6 from "@/image/6.png";
import Image7 from "@/image/7.png";
import Image8 from "@/image/8.png";
import Image9 from "@/image/9.png";
import Image10 from "@/image/10.png";
import Image11 from "@/image/11.png";
import Image12 from "@/image/12.png";
import Image13 from "@/image/13.png";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'], // 子集，通常 latin 即可
  weight: ['400', '700'], // 選擇你需要的字重，例如 '400' (Regular), '700' (Bold)
  display: 'swap',
  variable: '--font-roboto-condensed' // 指定 CSS 變數名稱
});

export const metadata = {
  title: "Whitee的數位履歷",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoCondensed.variable} antialiased`}
      >
        <main className="true"> {/* 保留這個 margin */}
          {children} {/* 這裡會渲染 (main)/layout.js */}
        </main>
      
        

        </body>
      </html>
    );
  }
  //測試
